name: Kodi Addon-Check

on: [push, pull_request]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
    - name: Check with addon-checker
      run: |
        kodi-addon-checker --branch omega plugin.video.channelsdvr
        kodi-addon-checker --branch omega plugin.video.hdhomerun.simple
        kodi-addon-checker --branch omega plugin.video.ispot.tv
        kodi-addon-checker --branch omega plugin.video.playonbrowser
        kodi-addon-checker --branch omega screensaver.bing
        kodi-addon-checker --branch omega screensaver.unsplash
        kodi-addon-checker --branch omega screensaver.system47
        kodi-addon-checker --branch omega screensaver.videosaver
        kodi-addon-checker --branch omega script.kodi.android.update
        kodi-addon-checker --branch omega script.kodi.windows.update
        kodi-addon-checker --branch omega script.module.pyhdhr